version: 2.1
jobs: 
  run_tests:
    docker: 
      - image: cimg/node:16.6.2
    steps:
    - checkout
    - run: 
        name: Hello world
        command: |
          echo 'Hello'
          apt update
          node --version



workflows: 
  version: 2.1

  build: 
    jobs: 
      - run_tests
