version: 2.1

executors:
  frontend:
    docker:
      - image: cimg/node:12.21.0
        environment:
          REACT_APP_URL: http://127.0.0.1
          REACT_APP_PORT: 5000
  backend:
    docker:
      - image: cimg/node:12.21.0
        environment:
          database_test: phantom_test
          user_test: postgres
          password_test: password
          host_test: localhost
          port: 5432
          ssl: 0
          jwtSecret: pern
      - image: circleci/postgres:13.4
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: phantom_test


commands: 
  server-packages:
    steps:
      - run:
          name: Install npm server packages
          command: |
            cd ~/project/server
            npm i
  client-packages:
    steps:
      - run: 
          name: Install npm client packages
          command: |
            cd ~/project/client
            npm i

jobs:
  frontend_lint:
    executor: frontend
    steps:
      - checkout
      - run: 
          name: Install npm packages
          command: |
            cd ~/project/client
            npm i
      - run:
          name: Run ESlint (Frontend)
          command: |
            cd ~/project/client
            npm run lint
  backend_lint:
    executor: backend
    steps:
      - checkout
      - run: 
          name: Install npm packages
          command: |
            cd ~/project/server
            npm i
      - run:
          name: Run ESlint (Backend)
          command: |
            cd ~/project/server
            npm run lint
  frontend_tests:
    executor: frontend
    steps:
      - checkout
      - run: 
          name: Install npm packages
          command: |
            cd ~/project/client
            npm i
      - run:
          name: Run tests
          command: |
            cd ~/project/client
            npm run test
  backend_tests:
    executor: backend
    steps:
      - checkout
      - run: 
          name: Install npm packages
          command: |
            cd ~/project/server
            npm i
      - run:
          name: Run tests
          command: |
            cd ~/project/server
            npm run test
  
  newman-collection-run:
    executor: backend
    steps:
      - checkout
      - server-packages
      - run:
          name: Run newman collection
          command: |
            cd ~/project/server
            sudo npm install -g newman
            npm start
            newman run postman/order_details.postman_collection\ .json 


workflows: 
  version: 2.1
  build: 
    jobs: 
      - frontend_lint
      - backend_lint
      - frontend_tests
      - backend_tests
