version: 2.1

executors:
  frontend:
    docker:
      - image: cimg/node:12.21.0
        environment:
          REACT_APP_URL: http://127.0.0.1
          REACT_APP_PORT: 5000
  backend:
    docker:
      - image: cimg/node:12.21.0
        environment:
          database_test: phantom_test
          user_test: postgres
          password_test: password
          host_test: localhost
          port: 5432
          ssl: 0
          jwtSecret_test: pern
      - image: circleci/postgres:13.4
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: phantom_test

jobs:
  fe_tests:
    executor: frontend
    steps:
      - checkout
      - run: 
          name: Install npm packages
          command: |
            cd ~/project/client
            npm i
      - run:
          name: Run tests
          command: |
            cd ~/project/client
            npm run test
  be_tests:
    executor: backend
    steps:
      - checkout
      - run: 
          name: Install npm packages
          command: |
            cd ~/project/server
            npm i
      - run:
          name: Run tests
          command: |
            cd ~/project/server
            npm run test

workflows: 
  version: 2.1
  build: 
    jobs: 
      - fe_tests
      - be_tests
