version: 2.1
jobs: 
  run_tests:
    docker: 
      - image: cimg/node:12.21.0
    steps:
    - checkout
    - run: 
        name: Hello world
        command: |
          echo 'Hello'
          node --version
          cd ~/project/client
          npm run test



workflows: 
  version: 2.1

  build: 
    jobs: 
      - run_tests
