version: 2.1
jobs: 
  run_tests:
    docker: 
      - image: buildpack-deps:stable
    steps:
    - checkout
    - run: 
        name: Hello world
        command: |
          echo 'Hello'
          apt update

workflows: 
  version: 2.1

  build: 
    jobs: 
      - run_tests
