version: 2.1

executors:
  frontend:
    docker:
      - image: cimg/node:12.21.0
        environment:
          REACT_APP_URL: http://127.0.0.1
          REACT_APP_PORT: 5000
  backend:
    docker:
      - image: cimg/node:12.21.0
        environment:
          database_test: phantom_test
          user_test: postgres
          password_test: test123
          host_test: localhost
          port_test: 5432
          ssl_test: 0
          jwtSecret_test: pern
      - image: circleci/postgres:13.4
        auth:
          username: postgres
          password: test123
        environment:
          - POSTGRES_PASSWORD=postgres


jobs:
  fe_tests:
    executor: frontend
    steps:
      - checkout
      - run: 
          name: Install npm packages
          command: |
            cd ~/project/client
            npm i
      - run:
          name: Run tests
          command: |
            cd ~/project/client
            npm run test
  be_tests:
    executor: backend
    steps:
      - checkout
      - run: 
          name: Install npm packages
          command: |
            cd ~/project/server
            npm i
      - run:
          name: Run tests
          command: |
            cd ~/project/server
            npm run test

          # sudo -u postgres psql
          # CREATE DATABASE phantom_test;
          # exit
          # cd ~/project/server
          # npm install
          # npm run test


workflows: 
  version: 2.1

  build: 
    jobs: 
      - fe_tests
      - be_tests
